"""add_auth_tracking_fields

Revision ID: f8d298b02e9f
Revises: 
Create Date: 2026-07-20 14:28:11.843112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d298b02e9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Helper to check if index exists in database
    connection = op.get_bind()
    
    def index_exists(table_name, index_name):
        result = connection.execute(
            sa.text(f"PRAGMA index_list({table_name})")
        ).fetchall()
        return any(row[1] == index_name for row in result)

    def column_exists(table_name, column_name):
        result = connection.execute(
            sa.text(f"PRAGMA table_info({table_name})")
        ).fetchall()
        return any(row[1] == column_name for row in result)

    # 1. Complaints indexes
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        if not index_exists('complaints', 'idx_complaints_filtering'):
            batch_op.create_index('idx_complaints_filtering', ['category', 'status', 'priority'], unique=False)
        if not index_exists('complaints', 'ix_complaints_assigned_to'):
            batch_op.create_index(batch_op.f('ix_complaints_assigned_to'), ['assigned_to'], unique=False)
        if not index_exists('complaints', 'ix_complaints_priority'):
            batch_op.create_index(batch_op.f('ix_complaints_priority'), ['priority'], unique=False)
        if not index_exists('complaints', 'ix_complaints_upvote_count'):
            batch_op.create_index(batch_op.f('ix_complaints_upvote_count'), ['upvote_count'], unique=False)

    # 2. Notifications indexes
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        if not index_exists('notifications', 'ix_notifications_notification_type'):
            batch_op.create_index(batch_op.f('ix_notifications_notification_type'), ['notification_type'], unique=False)

    # 3. Users columns (add as nullable first)
    with op.batch_alter_table('users', schema=None) as batch_op:
        if not column_exists('users', 'uuid'):
            batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))
        if not column_exists('users', 'registration_number'):
            batch_op.add_column(sa.Column('registration_number', sa.String(length=50), nullable=True))
        if not column_exists('users', 'phone'):
            batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        if not column_exists('users', 'last_login'):
            batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        if not column_exists('users', 'password_changed_at'):
            batch_op.add_column(sa.Column('password_changed_at', sa.DateTime(), nullable=True))
        if not column_exists('users', 'login_attempts'):
            batch_op.add_column(sa.Column('login_attempts', sa.Integer(), nullable=False, server_default='0'))
        if not column_exists('users', 'locked_until'):
            batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))

    # Populate existing users with unique UUIDs if not already populated
    import uuid
    users = connection.execute(sa.text("SELECT id, uuid FROM users")).fetchall()
    for user in users:
        # user[1] is uuid. If none or empty, generate and update
        if not user[1]:
            new_uuid = str(uuid.uuid4())
            connection.execute(
                sa.text("UPDATE users SET uuid = :uuid WHERE id = :id"),
                {"uuid": new_uuid, "id": user[0]}
            )

    # Now make uuid NOT NULL and create indexes
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('uuid', nullable=False, existing_type=sa.String(length=36))
        if not index_exists('users', 'idx_user_role_dept'):
            batch_op.create_index('idx_user_role_dept', ['role', 'department'], unique=False)
        if not index_exists('users', 'ix_users_department'):
            batch_op.create_index(batch_op.f('ix_users_department'), ['department'], unique=False)
        if not index_exists('users', 'ix_users_registration_number'):
            batch_op.create_index(batch_op.f('ix_users_registration_number'), ['registration_number'], unique=True)
        if not index_exists('users', 'ix_users_role'):
            batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        if not index_exists('users', 'ix_users_uuid'):
            batch_op.create_index(batch_op.f('ix_users_uuid'), ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_uuid'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_registration_number'))
        batch_op.drop_index(batch_op.f('ix_users_department'))
        batch_op.drop_index('idx_user_role_dept')
        batch_op.drop_column('locked_until')
        batch_op.drop_column('login_attempts')
        batch_op.drop_column('password_changed_at')
        batch_op.drop_column('last_login')
        batch_op.drop_column('phone')
        batch_op.drop_column('registration_number')
        batch_op.drop_column('uuid')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_notification_type'))

    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaints_upvote_count'))
        batch_op.drop_index(batch_op.f('ix_complaints_priority'))
        batch_op.drop_index(batch_op.f('ix_complaints_assigned_to'))
        batch_op.drop_index('idx_complaints_filtering')

    # ### end Alembic commands ###
